### PR TITLE
Upgrade Docusaurus to v2.3.1

### PR DESCRIPTION
**Pull request by ntolia**
## Description

This picks up a GTM fix and dependency security upgrades

## Does this PR need a docs update or release note?

- [x] :no_entry: No 

## Type of change

- [x] :bug: Bugfix
- [x] :world_map: Documentation

### CODE REVIEW

**Review by serverless-mom — COMMENTED** [review]
I'm not seeing Google Tag Manager tag showing up when I build the site after this update

**Comment by ntolia** [comment]
> I'm not seeing Google Tag Manager tag showing up when I build the site after this update

This is just the upgrade that has the fix. The actual GTM update is not needed but will show up in a subsequent PR.

**Comment by ntolia** [comment]
> I'm not seeing Google Tag Manager tag showing up when I build the site after this update

Oh, I missed what you said. Let me try something else and LMK what you see.

**Comment by ntolia** [comment]
@serverless-mom Are you running `make dev` or `npm run server` after a `make build`? I believe GTM stuff won't show up in dev builds.

**Comment by serverless-mom** [comment]
re-read the docs, that is the issue, it doesn't show up in dev builds, looks like expected behavior. Approving.

**Comment by ntolia** [comment]
@serverless-mom I see this in prod builds:
```
<script async="" src="https://www.googletagmanager.com/gtag/js?id=GTM-KM3XWPV"></script>
```

What's missing for you?

**Review by serverless-mom — APPROVED** [review]

**Comment by ntolia** [comment]
> @serverless-mom Are you running `make dev` or `npm run server` after a `make build`? I believe GTM stuff won't show up in dev builds.

Thank you for double checking!

**Pull request merged**
