### PR TITLE
exclude flaky integration test assertions

### PR DESCRIPTION
**Pull request by ryanfkeepers**
Comments out some particularly flaky test assertions. We have other assurances around this data already, so the exclusion is relatively safe.

---

#### Does this PR need a docs update or release note?

- [x] :no_entry: No

#### Type of change

- [x] :robot: Supportability/Tests

#### Test Plan

- [x] :green_heart: E2E

### CODE REVIEW

**Review by meain — APPROVED** [review]
I feel like we should at least actively track fixing this as this is a relatively important check, but let me approve to unblock.

**Comment by ryanfkeepers** [comment]
> I feel like we should at least actively track fixing this as this is a relatively important check, but let me approve to unblock.

Appreciated, and agreed about the fix.  I think we're going to have a difficult time improving the assertion case without also improving our stats gathering process.  But it is something to look forward to.

**Comment by ashmrtn** [comment]
if we no longer have information about when this is happening will we still have a way to debug it?

**Comment by ryanfkeepers** [comment]
> if we no longer have information about when this is happening will we still have a way to debug it?

Have we ever debugged any code based on these assertions?  To my recollection, we have not.

**Pull request merged**
