### PR TITLE
print stats after backup

### PR DESCRIPTION
**Pull request by ryanfkeepers**
Prints backup stats to the CLI following completion.  In case of multiple users, the stats for each backup is printed at the end of the backup, rather than at the end of the command.

---

#### Does this PR need a docs update or release note?

- [x] :white_check_mark: Yes, it's included

#### Type of change

- [x] :sunflower: Feature

#### Test Plan

- [x] :muscle: Manual
- [x] :zap: Unit test

### CODE REVIEW

**Comment by ryanfkeepers** [comment]
Some examples:

Single user
```
Backing up data:      1s done
Done - ID: 4897f340-3d9a-4684-9d68-916b871b2995

  Started At            Duration   Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  2023-04-14T18:50:57Z  4.747972s  9.3 kB          2               0              0

Completed Backups:
  Started At            ID                                    Status     Resource Owner
  2023-04-14T18:50:57Z  4897f340-3d9a-4684-9d68-916b871b2995  Completed  rfinders@10rqc2.onmicrosoft.com
```

Multiple users
```
Backing up data:      1s done
Done - ID: e083fbfc-b329-40d2-ac3c-03ac90a4b616

  Started At            Duration   Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  2023-04-14T18:50:04Z  4.633666s  9.3 kB          2               0              0

# ... skipping standard output
Backing up data:      1s done
Done - ID: 9153c4e5-631a-4f60-bd03-f0c620cdb567

  Started At            Duration   Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  2023-04-14T18:50:10Z  4.599102s  9.3 kB          2               0              0

Completed Backups:
  Started At            ID                                    Status     Resource Owner
  2023-04-14T18:50:04Z  e083fbfc-b329-40d2-ac3c-03ac90a4b616  Completed  rfinders@10rqc2.onmicrosoft.com
  2023-04-14T18:50:10Z  9153c4e5-631a-4f60-bd03-f0c620cdb567  Completed  lynner@10rqc2.onmicrosoft.com
```

with --json
```
Backing up data:      1s done
Done - ID: 7be8b3bc-3163-4766-b695-1662a91f68f4

{
  "bytesRead": 1752,
  "bytesUploaded": 9296,
  "endedAt": "2023-04-14T12:52:13.943881-06:00",
  "errorCount": 0,
  "itemsRead": 2,
  "itemsSkipped": 0,
  "itemsWritten": 2,
  "startedAt": "2023-04-14T12:52:09.195463-06:00"
}


Completed Backups:
[
  {
    "id": "7be8b3bc-3163-4766-b695-1662a91f68f4",
    "errorCount": 0,
    "startedAt": "2023-04-14T12:52:09.195463-06:00",
    "status": "Completed",
    "version": "0",
    "bytesRead": 1752,
    "bytesUploaded": 9296,
    "owner": "rfinders@10rqc2.onmicrosoft.com"
  }
]
```

**Comment by ryanfkeepers** [comment]
v2

two users, standard output
```
Connecting to repository:      3s done
Connecting to M365:         done
Backing Up ∙ rfinders@10rqc2.onmicrosoft.com
Discovering items to backup:      2s done
∙ contacts:      1s done
Backing up data:      1s done
Done

  ID                                    Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  7f6a8155-83df-48a7-8770-cc1eafb2bc2f  14 kB           6               0              0

Connecting to M365:         done
Backing Up ∙ pattif@10rqc2.onmicrosoft.com
Discovering items to backup:      2s done
∙ contacts:      1s done
Backing up data:      0s done
Done

  ID                                    Bytes Uploaded  Items Uploaded  Items Skipped  Errors
  c12e03c2-8186-4474-b843-4fa2cc88bd73  9.6 kB          2               0              0

Completed Backups:
  ID                                    Started At            Duration   Status     Resource Owner         
  7f6a8155-83df-48a7-8770-cc1eafb2bc2f  2023-04-19T20:32:48Z  4.105784s  Completed  rfinders@10rqc2.onmicrosoft.com
  c12e03c2-8186-4474-b843-4fa2cc88bd73  2023-04-19T20:32:54Z  3.124126s  Completed  pattif@10rqc2.onmicrosoft.com
```

two users json output
```
Connecting to repository:      2s done
Connecting to M365:         done
Backing Up ∙ rfinders@10rqc2.onmicrosoft.com
Discovering items to backup:      2s done
∙ contacts:      1s done
Backing up data:      1s done
Done - ID: 61be6630-c30e-43b9-b14d-75ec6ce3c2b8

Connecting to M365:         done
Backing Up ∙ pattif@10rqc2.onmicrosoft.com
Discovering items to backup:      2s done
∙ contacts:      1s done
Backing up data:      0s done
Done - ID: 5e85efde-222c-4a91-9137-d417593f2f1c

Completed Backups:
[
  {
    "id": "61be6630-c30e-43b9-b14d-75ec6ce3c2b8",
    "status": "Completed",
    "version": "0",
    "owner": "rfinders@10rqc2.onmicrosoft.com",
    "stats": {
      "id": "61be6630-c30e-43b9-b14d-75ec6ce3c2b8",
      "bytesRead": 790,
      "bytesUploaded": 9295,
      "endedAt": "2023-04-19T14:34:12.673998-06:00",
      "errorCount": 0,
      "itemsRead": 2,
      "itemsSkipped": 0,
      "itemsWritten": 2,
      "startedAt": "2023-04-19T14:34:08.038245-06:00"
    }
  },
  {
    "id": "5e85efde-222c-4a91-9137-d417593f2f1c",
    "status": "Completed",
    "version": "0",
    "owner": "pattif@10rqc2.onmicrosoft.com",
    "stats": {
      "id": "5e85efde-222c-4a91-9137-d417593f2f1c",
      "bytesRead": 786,
      "bytesUploaded": 9296,
      "endedAt": "2023-04-19T14:34:18.27272-06:00",
      "errorCount": 0,
      "itemsRead": 2,
      "itemsSkipped": 0,
      "itemsWritten": 2,
      "startedAt": "2023-04-19T14:34:14.25937-06:00"
    }
  }
]
```

**Review by gmatev — APPROVED** [review]
Looks great from output POV!

**Review by meain — COMMENTED** [review]
LGTM, but I feel like the numbers can be a bit misleading to the user because of the following reasons:

- We count the `details` and `parentPaths` file in metadata for the count and size
- `.meta` and `.dirmeta` files are counted

Also, 

- Folders are treated as `items` (should we have a separate section?)
- Maybe we should mention about deletions?

**Comment by ryanfkeepers** [comment]
>  I feel like the numbers can be a bit misleading to the user

100% agreed.  However, these are long established issues, and are outside the scope of this change.

@gmatev I'd like to merge this, sounds like abin is good with the code.  Can we refine the numbers as a follow-up?  Or should I keep this data hidden for now?

**Pull request merged**
