### PR TITLE
Rackspace blog post

### PR DESCRIPTION
**Pull request by ntolia**
## Description

Adds a slightly-edited version of the Rackspace blog post.

### CODE REVIEW

**Review by serverless-mom — APPROVED** [review]
Screen Shot 2022-12-15 at 9 29 52 AM
This looks good but I do notice that the blog switched to light mode. was this intentional?

**Comment by serverless-mom** [comment]
looks like we've got overflow into the top bar
Screen Shot 2022-12-15 at 9 51 29 AM

**Comment by serverless-mom** [comment]
dark/light mode is working as expected

**Comment by ntolia** [comment]
> looks like we've got overflow into the top bar 

@serverless-mom What browser are you using? I cannot repro this on Chrome or Safari. I suspect this is some local plugin on your side.

**Review by gmatev — APPROVED** [review]

**Pull request merged**
