### PR TITLE
Docusaurus setup for versioned docs

### PR DESCRIPTION
**Pull request by meain**
## Description

This will allow us to have versioned docs.

- Header will have something like this to change the version of docs  with it landing on the latest by default.
    
- Footer changed from "Version" to "Latest Version" as we might be on a different version.
    
- Added v0.0.3 as the first set of version.
- Once a release is done, the CI will now create a pull request to the repo to add the new versioned set of docs ([example](https://github.com/alcionai/corso/pull/1709)).

## Type of change

- [ ] :sunflower: Feature
- [ ] :bug: Bugfix
- [x] :world_map: Documentation
- [ ] :robot: Test
- [ ] :computer: CI/Deployment
- [ ] :hamster: Trivial/Minor

## Issue(s)

* fixes https://github.com/alcionai/corso/issues/1601

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Comment by ntolia** [comment]
@meain I know I asked for this but given that you have a way of pushing docs without changing versions from the last tag, do we really need this right now? Maybe we add this sometime next year?

**Comment by meain** [comment]
I had a similar thought when I [initially suggested](https://github.com/alcionai/corso/issues/1601#issuecomment-1328965680) about just generating the versioned docs on the fly. The problem is that, although we display the version number as the latest tag we have no way of figuring what parts of the content is for the latest version vs what is for the next version. For example if we have a doc fix for v1.0, but have some doc changes (like addition/removal of an option) for the upcoming release, the next time we publish the website, both of these changes make it to the website under the latest version. We can hack around this by using the old history to generate the docs, but the sidebar file can cause problems.

**Comment by meain** [comment]
FYI, this now means that we will have generated docs in the tree for versioned docs.

**Comment by ntolia** [comment]
> I had a similar thought when I [initially suggested](https://github.com/alcionai/corso/issues/1601#issuecomment-1328965680) about just generating the versioned docs on the fly. The problem is that, although we display the version number as the latest tag we have no way of figuring what parts of the content is for the latest version vs what is for the next version. 

Yes, I agree this is a problem but I think we are safe in terms of churn and expectations here for a couple of months. Let's push this PR in in a couple of months but not pay the overhead right now.

**Comment by meain** [comment]
Makes sense, I'll close the PR but keep the issue open with it removed from current dev cycle.

**Pull request closed without merging**
