### PR TITLE
Add parent path information to malware detected items

### PR DESCRIPTION
**Pull request by vkamra**
This allows identifying the file location when an item is detected with malware

---

#### Does this PR need a docs update or release note?

- [x] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [ ] :no_entry: No

#### Type of change

- [ ] :sunflower: Feature
- [x] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Supportability/Tests
- [ ] :computer: CI/Deployment
- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* #3112 

#### Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Review by ryanfkeepers — APPROVED** [review]
LGTM.  While we're in this code, we might want to add the drive ID as well, since we'll need that for identification in multi-drive environments like sharepoint.

**Comment by vkamra** [comment]
> LGTM. While we're in this code, we might want to add the drive ID as well, since we'll need that for identification in multi-drive environments like sharepoint.

SGTM - will push a follow up

**Comment by vkamra** [comment]
> I know this merged, but sidebar question: we're trying to standardize what locations look like so it's easier for SDK users to consume them. The format we seem to have settled on for backup details OneDrive/SharePoint items is `root:/<set of display name folders>`. Will this adhere to that?

This will not adhere to that. Good call out. @ashmrtn - confirm once we have that locked down and I can make that change here.

**Comment by ashmrtn** [comment]
circling back to this (sorry, lost track of it), locationRefs for OneDrive are formatted as stated in the original comment: `root:/<set of display name folders>`. Information about drive name/drive ID are passed in separate fields in folder entries in backup details

**Pull request merged**
