### PR TITLE
Correct default value for s3 endpoint

### PR DESCRIPTION
**Pull request by neha-Gupta1**
Use default values from endpoint only if its not present in config file

#### Does this PR need a docs update or release note?

- [ ] :no_entry: No

#### Type of change

- [ ] :bug: Bugfix

#### Issue(s)

* #<issue>

#### Test Plan

- [ ] :muscle: Manual

### CODE REVIEW

**Review by meain — COMMENTED** [review]
The changes seem to work for me. Not sure how difficult it would be, but we should consider adding tests for the config, env, cli interaction if possible.

**Comment by neha-Gupta1** [comment]
@meain I have added few test cases for the creds. And will add more testcases for s3 configs. Is it okay if I raise another PR for that ASAP?

**Comment by neha-Gupta1** [comment]
[PR](https://github.com/alcionai/corso/pull/3727) test-cases for config files and flags

**Review by meain — APPROVED** [review]
LGTM

**Pull request merged**
