### PR TITLE
print location of log file

### PR DESCRIPTION
**Pull request by ryanfkeepers**
## Does this PR need a docs update or release note?

- [x] :no_entry: No 

## Type of change

- [x] :broom: Tech Debt/Cleanup

## Issue(s)

* #2329

## Test Plan

- [x] :muscle: Manual

### CODE REVIEW

**Comment by ryanfkeepers** [comment]
```
> corso backup create onedrive
Logging to file: /Users/keepers/go/src/github.com/alcionai/.corso.log
Connecting to repository:      2s ●∙∙
```

**Comment by vkamra** [comment]
@ryanfkeepers - the output when we display usage is a bit ugly. Any way we can have this not show up in those cases?

```
$ ./corso
Logging to file: /Users/vaibhavkamra/Library/Logs/corso/logs/2023-02-01T01-19-54Z.log
Free, Secure, and Open-Source Backup for Microsoft 365.

Usage:
  corso [flags]
  corso [command]

Available Commands:
  backup      Backup your service data
  env         env var guide
  help        Help about any command
  repo        Manage your repositories
  restore     Restore your service data

Flags:
      --config-file string   config file location (default "$HOME/.corso.toml")
      --debug-api-calls      add non-2xx request/response errors to logging
  -h, --help                 help for corso
      --hide-progress        turn off the progress bar displays
      --json                 output data in JSON format
      --log-file string      location for writing logs, use '-' for stdout (default "corso-<timestamp>.log")
      --log-level string     set the log level to debug|info|warn|error (default "info")
      --no-stats             disable anonymous usage statistics gathering
      --retain-progress      retain the progress bar displays after completion
  -v, --version              current version info

Use "corso [command] --help" for more information about a command.
```

**Review by vkamra — APPROVED** [review]

**Comment by vkamra** [comment]
Can merge and iterate

**Comment by ntolia** [comment]
Not for this PR but It would be great to only display the log file when running a command vs. displaying help text.

**Pull request merged**
