### PR TITLE
Address review feedback from #1896

### PR DESCRIPTION
**Pull request by vkamra**
## Description

- Adds accessor methods for size/modified
- Do not initialize folder in test with a modified time

## Does this PR need a docs update or release note?

- [x] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [ ] :no_entry: No 

## Type of change

- [ ] :sunflower: Feature
- [ ] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :computer: CI/Deployment
- [x] :hamster: Trivial/Minor

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Review by rajatkateja — APPROVED** [review]
LGTM. 

One corner case: what happens if there is an empty folder? Do we not back it up at all and hence it never shows in the details?  
And on a related note: is `AddFoldersForItem` always called on an item or is it called on folders too?

**Comment by vkamra** [comment]
> One corner case: what happens if there is an empty folder? Do we not back it up at all and hence it never shows in the details?

Empty folders are not backed up (@ashmrtn - correct me if I'm wrong?)

> And on a related note: is `AddFoldersForItem` always called on an item or is it called on folders too?

Yep - `AddFoldersForItem` is always called for an item.

**Comment by ashmrtn** [comment]
>Empty folders are not backed up

I think we're actually inconsistent on this point. We've never really decided on if there needs to be a fixed behavior

As far as I know, OneDrive will skip empty folders because it can infer which folders are not empty by examining the paths of items. Exchange will create empty folders because we need to find a folder before we know if it has items in it. Incrementals will create new backups that do not have empty folders if the folder was already empty in the base snapshot for the incremental (i.e. folder foo in the base had no items -> it will not appear in the new backup. If folder foo had an item in the base but the item was deleted in the new backup then foo will still appear in the new backup but it will be empty)

**Comment by rajatkateja** [comment]
Yeah, this sounds pretty inconsistent. I think it is fine for now (Ark preview) but can we track making this consistent somewhere just so we don't forget about it? Thanks!

**Pull request merged**
