### PR TITLE
log observed messages

### LINKED ISSUE #2061: Log /observe'd data
## Issue
Corso is lacking in supportability coverage, especially involving logging and other telemetry.  Info-level logging is notably missing.  However, in the CLI, we have much greater communication due to the /observe package tracking phases and items as they're processed.  We can streamline our logging by hooking into /observe and having it log info- and debug-level details that mimic the titles we display during progress.

## Acceptance Criteria
* Log all processing phase (connection to x, downloading all y, etc) observes at info level.
* Log all per-item downloads (downloading mail item x, downloading file y, etc) observes at debug level.
* Containers (retrieving all mail in inbox, getting all files in /a/b/c) could go either way; start with info level.
* PII redaction is not part of this issue.

### PR DESCRIPTION
**Pull request by ryanfkeepers**
## Description

add logging to the observe package, assume that
every instance where a message is observed, it
also gets logged.

Merger may want to wait until logging to a file is the standard behavior, else the terminal might get messy/buggy.

## Does this PR need a docs update or release note?

- [x] :no_entry: No 

## Type of change

- [x] :broom: Tech Debt/Cleanup

## Issue(s)

* closes #2061

## Test Plan

- [x] :muscle: Manual

### CODE REVIEW

**Comment by vkamra** [comment]
@meain - can you file a ticket and look into enabling logging to a file by default? This will allow us to merge additional logging PRs such as this one.

**Comment by meain** [comment]
Added https://github.com/alcionai/corso/issues/2076 to track writing logs to disk by default.

**Review by meain — APPROVED** [review]
LGTM, but we should wait till https://github.com/alcionai/corso/pull/2082 gets merged.

**Comment by meain** [comment]
https://github.com/alcionai/corso/pull/2082 is now in, we can probably merge this in now. @ryanfkeepers

**Pull request merged**
