### PR TITLE
Add misc typo fixes

### PR DESCRIPTION
**Pull request by pandeyabs**
---

#### Does this PR need a docs update or release note?

- [ ] :no_entry: No

#### Type of change

- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* #<issue>

#### Test Plan

- [ ] :muscle: Manual

### CODE REVIEW

**Comment by ryanfkeepers** [comment]
@pandeyabs Is this waiting on anything before going into the merge queue?

**Comment by ashmrtn** [comment]
rip spell check linter 😭

**Comment by ryanfkeepers** [comment]
> rip spell check linter 😭

We barely knew ye.

**Comment by pandeyabs** [comment]
> @pandeyabs Is this waiting on anything before going into the merge queue?

Oops. I'll get it in today.

**Pull request merged**
